### ISSUE TITLE
Add RxCocoa observables support

### ISSUE THREAD

**Issue by reececomo** [hubrioAU/XRouter#11]
**What is your feature request**
Add observable/single versions of the `transition(to:)`/`openURL(_:)` methods for RxCocoa users

**What problem would it solve**
Allows observable chaining/`andThen` support in RxSwift/RxCocoa

**Comment by farabi** [comment]
Hello. 

Thank you for this great library.
I'm actually new to open source project, and i want to do my first contribution through this task.

Perhaps if you can give me more details, i can give a hand.

In order to have an observable openURL, you will need to add an RxSwift as a dependency right ?
So would you add a new extension, kind of RxRouter ?

Regards 👍

**Comment by reececomo** [comment]
Thanks @farabi!

Take a look at Moya’s Rx implementation doc here:
https://github.com/Moya/Moya/blob/master/docs/RxSwift.md

And how this library has done it here https://github.com/quickbirdstudios/XCoordinator/tree/master/XCoordinator/Classes/RxSwift

I think this type of approach is something we could emulate - was going to give it a crack over the weekend but happy to take a backseat if you have ideas here

**Comment by farabi** [comment]
Hello @reececomo.

Thank you for the explanation. I got your point !
I'm currently working on it. you can assign this issue to me.

**Comment by reececomo** [comment]
Hi @farabi thanks for volunteering. I was able to add the RxSwift extension (https://github.com/hubrioAU/XRouter/pull/16) so I am going to close this ticket. There's still heaps of other things that could be done, so feel free to submit follow-up PRs for other features 👍
